"""Add cover_letter_count_this_month

Revision ID: 0355683f6232
Revises: 17f81d4150b9
Create Date: 2026-06-22 00:46:50.743798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0355683f6232'
down_revision = '17f81d4150b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_letter_count_this_month', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cover_letter_count_this_month')

    # ### end Alembic commands ###
